In [1]:
import pandas as pd
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import mean_squared_error
from sklearn.datasets import fetch_california_housing


housing=fetch_california_housing()
print(housing)

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
          37.88      , -122.23      ],
       [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
          37.86      , -122.22      ],
       [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
          37.85      , -122.24      ],
       ...,
       [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
          39.43      , -121.22      ],
       [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
          39.43      , -121.32      ],
       [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
          39.37      , -121.24      ]], shape=(20640, 8)), 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)), 'frame': None, 'target_names': ['MedHouseVal'], 'feature_names': ['MedInc', 'HouseAge', 'AveRooms', 'AveBedrms', 'Population', 'AveOccup', 'Latitude', 'Longitude'], 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib:\nhttps://lib.stat.cmu.edu/datasets/houses.zip\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [2]:
housing

{'data': array([[   8.3252    ,   41.        ,    6.98412698, ...,    2.55555556,
           37.88      , -122.23      ],
        [   8.3014    ,   21.        ,    6.23813708, ...,    2.10984183,
           37.86      , -122.22      ],
        [   7.2574    ,   52.        ,    8.28813559, ...,    2.80225989,
           37.85      , -122.24      ],
        ...,
        [   1.7       ,   17.        ,    5.20554273, ...,    2.3256351 ,
           39.43      , -121.22      ],
        [   1.8672    ,   18.        ,    5.32951289, ...,    2.12320917,
           39.43      , -121.32      ],
        [   2.3886    ,   16.        ,    5.25471698, ...,    2.61698113,
           39.37      , -121.24      ]], shape=(20640, 8)),
 'target': array([4.526, 3.585, 3.521, ..., 0.923, 0.847, 0.894], shape=(20640,)),
 'frame': None,
 'target_names': ['MedHouseVal'],
 'feature_names': ['MedInc',
  'HouseAge',
  'AveRooms',
  'AveBedrms',
  'Population',
  'AveOccup',
  'Latitude',
  'Longitude'],
 'DESCR': '.. _california_housing_dataset:\n\nCalifornia Housing dataset\n--------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 20640\n\n:Number of Attributes: 8 numeric, predictive attributes and the target\n\n:Attribute Information:\n    - MedInc        median income in block group\n    - HouseAge      median house age in block group\n    - AveRooms      average number of rooms per household\n    - AveBedrms     average number of bedrooms per household\n    - Population    block group population\n    - AveOccup      average number of household members\n    - Latitude      block group latitude\n    - Longitude     block group longitude\n\n:Missing Attribute Values: None\n\nThis dataset was obtained from the StatLib:\nhttps://lib.stat.cmu.edu/datasets/houses.zip\n\nThe target variable is the median house value for California districts,\nexpressed in hundreds of thousands of dollars ($100,000).\n\nThis dataset was derived from the 1990 U.S. census, using one row per census\nblock group. A block group is the smallest geographical unit for which the U.S.\nCensus Bureau publishes sample data (a block group typically has a population\nof 600 to 3,000 people).\n\nA household is a group of people residing within a home. Since the average\nnumber of rooms and bedrooms in this dataset are provided per household, these\ncolumns may take surprisingly large values for block groups with few households\nand many empty houses, such as vacation resorts.\n\nIt can be downloaded/loaded using the\n:func:`sklearn.datasets.fetch_california_housing` function.\n\n.. rubric:: References\n\n- Pace, R. Kelley and Ronald Barry, Sparse Spatial Autoregressions,\n  Statistics and Probability Letters, 33:291-297, 1997.\n'}

In [5]:
# Preparing the dataset

data=pd.DataFrame(housing.data,columns=housing.feature_names)
data.sample(10)

       MedInc  HouseAge  AveRooms  ...  AveOccup  Latitude  Longitude
17386  1.7941      22.0  4.216146  ...  3.929688     34.97    -120.44
14096  2.0500      11.0  3.571111  ...  3.075556     32.75    -117.11
12883  3.0417      35.0  4.798507  ...  2.470149     38.67    -121.34
10590  5.1299      16.0  5.776413  ...  3.106880     33.69    -117.78
3361   2.2661      16.0  5.783051  ...  3.174576     40.37    -120.58
281    6.7527      23.0  7.064024  ...  2.911585     37.80    -122.18
11385  7.3719      22.0  7.104592  ...  2.770408     33.66    -117.95
15755  3.3500      52.0  4.783002  ...  2.305606     37.77    -122.45
1588   8.0030      18.0  7.812339  ...  2.810626     37.82    -121.98
2113   1.4107      29.0  4.247444  ...  3.858896     36.76    -119.75

[10 rows x 8 columns]

In [7]:
data['price']=housing.target
data.sample(10)

        MedInc  HouseAge   AveRooms  ...  Latitude  Longitude  price
12890   3.6786      27.0   5.929078  ...     38.64    -121.37  1.597
3938    5.6345      35.0   5.470085  ...     34.22    -118.58  2.282
11092   3.7604      15.0   5.804143  ...     33.81    -117.87  2.801
4102    5.5683      19.0   5.287500  ...     34.14    -118.39  3.092
15261   6.3712       9.0   6.762044  ...     33.02    -117.26  3.698
737     3.1734      38.0   6.060241  ...     37.67    -122.13  1.816
14751   4.6364      17.0   6.169863  ...     32.57    -117.06  1.411
1566   15.0001       2.0  22.222222  ...     37.74    -121.96  3.500
8539    4.0727      18.0   3.957845  ...     33.90    -118.36  2.140
3153    3.2405      16.0   6.113772  ...     35.12    -118.46  0.855

[10 rows x 9 columns]

In [8]:
from urllib.parse import urlparse
X=data.drop(columns=['price'])
y=data['price']

In [9]:
xtrain,xtest,ytrain,ytest=train_test_split(X,y,random_state=42,test_size=0.2)
from mlflow.models import infer_signature
signature=infer_signature(xtrain,ytrain)

param_grid={
    'n_estimators':[100,200],
    'max_depth':[5,10,None],
    'min_samples_split':[2,5],
    'min_samples_leaf':[1,2]
}

In [11]:
# Hyper parameter tuning using gridsearchCV

def hyperParameterTuner(xtrain,ytrain,param_grid):
    rf=RandomForestRegressor()
    gridsearch=GridSearchCV(estimator=rf,param_grid=param_grid,cv=5,n_jobs=1,verbose=2,scoring="neg_mean_squared_error")

    gridserach.fit(xtrain,ytrain)
    return gridsearch

In [ ]:
with mlflow.start_run():
    grid_search=hyperParameterTuner(xtrain,ytrain,param_grid)
    # get the best model
    best_model=grid_search.best_estimator_
    # evaluate the best model
    ypred=best_model.predict(xtest)
    mse=mean_squared_error(ytest,ypred)
    # log best parameters and metrics
    mlflow.log_param("best_n_estimators",grid_search.best_params_['n_estimators'])
    mlflow.log_param("best_max_depth",grid_search.best_params_['max_depth'])
    mlflow.log_param("best_min_samples_split",grid_search.best_params_['min_samples_split'])
    mlflow.log_param("best_min_samples_leaf",grid_search.best_params_['min_samples_leaf'])
    mlflow.log_metric("mse",mse)

    # Tracking url